# Presentación {.unnumbered}

Bienvenidos al tercer libro sobre Investigaciones en Gestión del Riesgo de Desastres para Colombia. Este libro reúne trabajos recientes que exploran el riesgo de desastres desde una perspectiva integral reconociendo la interconexión entre humanos, paisaje y animales y múltiples enfoques incorporando las realidades culturales, territoriales y ecológicas de nuestro país.

Por primera vez este libro se diseña como un recurso abierto y accesible para todos. La versión digital está disponible libremente para todo público con el fin de fomentar la difusión del conocimiento, la colaboración y la replicabilidad de la ciencia.

A lo largo del libro, los lectores encontrarán no solo análisis teóricos, sino una diversidad de temas que reflejan nuestro compromiso con una gestión del riesgo de desastres que abarque metodologías participativas (como la cartografía), estudios multitemporales de resiliencia y estudios de caso centrados en animales de producción frente a amenazas volcánicas. Cada capítulo se diseñó para aportar tanto al conocimiento académico como con herramientas para la acción comunitaria y gubernamental.

Agradecemos por difundir el libro para que crezca como un espacio de reflexión y acción para la gestión del riesgo de desastres en Colombia.

Ana Milena Prada Uribe, Subdirectora para el Conocimiento del Riesgo de Desastres