---
title: "2. Enfoque Etnodiferencial y Riesgo de Desastre en Colombia: Líneas de Fuga para una Digna Vida"
author:
  - name: William Oswaldo Gaviria-Gutiérrez ^1^
    orcid: 0000-0003-4228-4665
    affiliation: "^1^Observatorio Psicosocial para la Gestión del Riesgo de Desastres, Facultad de Ciencias Sociales y Humanas, Programa de Psicología, Universidad de Manizales. Cra 9a 19-03, Manizales, Colombia" 
    corresponding: true
    email: "wgaviria@umanizales.edu.co"
  - name: Lina Andrea Zambrano-Hernández ^1^
    orcid: 0000-0002-6151-9148
date: "12-01-2025"
title-block-banner: bannerc1.png
title-block-banner-color: "white"
css:
  - custom.css
  - pdf-styles.css
format:
  html:
    theme: cosmo
    toc: true
    number-sections: false
  pdf:
    documentclass: article
    geometry: margin=1in
    number-sections: false
    include-in-header:
      - text: |
          \usepackage{graphicx}
          \usepackage{xcolor}
          \usepackage{fancyhdr}
          \usepackage{wallpaper}
    title-block-banner: bannerc1.png
    colorlinks: true
    keep-tex: true
bibliography: capitulo2-references.bib

crossref:
  fig-prefix: "Figura"
  tbl-prefix: "Tabla"
  chapters: false
---

::: {#resumen}
# Resumen

En Colombia, la gestión del riesgo de desastres ha reflejado la subalternización histórica de las voces comunitarias al percibir la diferencia cultural como un obstáculo en lugar de una potencialidad. Este reflejo es posible en tanto se ha sostenido un orden social que privilegia la homogenización por encima de las realidades situadas. Para reconfigurar esta práctica relacional, es prioritario reconocer la riqueza inherente a las comunidades. Dada la constante exposición del país a fenómenos naturales, un enfoque que trascienda la recopilación de datos es fundamental. Este estudio abordó las posibilidades de articulación del enfoque etnodiferencial en la Gestión del Riesgo de Desastres (GRD) en Colombia. Para ello, se desarrolló una investigación de corte cualitativo que incluyó la realización de seis grupos focales y catorce entrevistas a profundidad con representantes comunitarios e institucionales. Estos instrumentos permitieron explorar la diversidad de perspectivas sobre el desastre y facilitaron el surgimiento de conocimientos arraigados en el diálogo y la interacción, visibilizando las voces históricamente silenciadas. El principal hallazgo implica reconocer que desmantelar la noción de subalternidad y adoptar una visión diversa no solo conduce a una reducción del sufrimiento, sino que también promueve la justicia, la dignidad y el reconocimiento de todas las voces. En conclusión, la investigación demostró que el enfoque etnodiferencial puede redefinir la GRD al centrarse en el diálogo y el respeto por la diversidad como elementos esenciales para transformar la relación entre las comunidades y las instituciones. Esta perspectiva tensiona los límites tradicionales de la gestión del riesgo, abriendo el camino hacia un proceso auténticamente humano. Se confirma que cada cultura y experiencia comunitaria aporta un valor único al panorama general, lo que permite una comprensión integral y una respuesta eficaz a los desastres.

**Palabras clave:** subalternización\index{Subalternización}, gestión del riesgo de desastres\index{Gestión del riesgo de desastres}, etnodiferencial\index{Etnodiferencial}, diversidad\index{Diversidad}, justicia\index{Justicia}.
:::

::: {#abstract}
# Ethno-differential approach and disaster risk in Colombia: lines of flight for a dignified life

**Abstract**. In Colombia, disaster risk management has reflected the historical subalternization of community voices by perceiving cultural difference as an obstacle rather than a potentiality. This reflection is possible insofar as a social order has been sustained that privileges homogenization over situated realities. To reconfigure this relational practice, recognizing the inherent richness of communities is a priority. Given the country's constant exposure to natural phenomena, an approach that transcends mere data collection is fundamental. This study addressed the potential integration of the ethno-differential approach into Disaster Risk Management (DRM) in Colombia. To this end, a qualitative research design was developed, which included conducting six focus groups and fourteen in-depth interviews with community and institutional representatives. These instruments enabled the exploration of diverse perspectives on disasters and facilitated the emergence of knowledge rooted in dialogue and interaction, giving visibility to historically silenced voices. The main finding underscores the importance of dismantling the notion of subalternity and adopting a diverse vision, which not only leads to a reduction in suffering but also promotes justice, dignity, and the recognition of all voices. In conclusion, the research demonstrated that the ethno-differential approach could redefine DRM by focusing on dialogue and respect for diversity as essential elements for transforming the relationship between communities and institutions. This perspective challenges the traditional boundaries of disaster risk management, paving the way for a genuinely human process. It is confirmed that each culture and community experience contributes a unique value to the broader picture, enabling a comprehensive understanding and an effective response to disasters.

**Keywords**: subalternization, risk management, ethno-differential, diversity, justice.
:::

# 1. INTRODUCCIÓN

El desastre es una ruptura de la cotidianidad. En un territorio específico, las interacciones socioambientales que se han venido configurando se fracturan, lo que genera un profundo sufrimiento para el cuerpo subjetivo, político y territorial. Evitar este dolor representa un acto de justicia\index{justicia} con la digna vida\index{digna vida}, en tanto aquel padecimiento es evitable. Así, en clave de promoción de la digna vida y evitación de sufrimientos emerge la gestión del riesgo de desastres (GRD), concebida como un proceso social orientado a la transformación de las relaciones entre los seres humanos y la naturaleza [@narvaez2009].

Ahora bien, aun cuando su horizonte es loable, la GRD se ha visto inmersa en una tensión discursiva desde hace varios años. Por un lado, encontramos el enfoque que comprende el desastre desde una perspectiva fisicalista\index{enfoque fisicalista}, que privilegia el estudio de las amenazas por encima de cualquier otro factor [@torrico2008]. Por otro lado, existen los planteamientos construccionistas, que interpretan el riesgo y el desastre como fenómenos emergentes de la compleja red de interacciones humanas [@maskrey1998; @alcantara2025].

Esta tensión no es menor, en tanto el ángulo de colocación-acción que soportan determinará los procesos que han de llevarse a cabo. Al elegir una visión fisicalista, se podría desatender el diálogo sobre el desarrollo social, aunque se logren avances significativos en la comprensión de los procesos naturales subyacentes. En contraste, optar por un enfoque construccionista\index{enfoque construccionista} puede llevar a una menor atención a los procesos físicos, pero proporciona un marco más rico para entender cuestiones de desigualdad social, exclusión, segregación, vulnerabilidad y desarrollo de capacidades.

Esta divergencia en los enfoques resalta la complejidad inherente al riesgo y al desastre, que son fenómenos multifacéticos y no lineales. Indistintamente del enfoque que se elija, no puede perderse de vista el horizonte de digna vida\index{horizonte de digna vida} tanto para los seres humanos como para aquellos que no. La GRD implica un marco de enunciación ético-político en defensa de la vida. Este contexto invita al reconocimiento de sus múltiples tramas y a la necesidad de diálogos interdisciplinarios para abordar el problema de manera integral [@commoner1973; @capra2014].

Sin embargo, el desarrollo de un diálogo significativo es posible solo cuando todos los participantes tienen igual relevancia en el discurso. Lamentablemente, esta igualdad no siempre se logra, como lo señaló Spivak al afirmar: "el subalterno no es un sujeto que ocupa una posición discursiva desde la que puede hablar o responder [...] es el espacio en blanco entre las palabras; el hecho de que se le silencie no significa que no exista" [@spivak2003].

La noción de subalterno\index{subalterno} subraya el reconocimiento de grupos sociales que históricamente han sido silenciados e ignorados, pero que, como lo ha demostrado la investigación, son los más afectados por los desastres. Mujeres, comunidades diversas sexual y funcionalmente, afrodescendientes, indígenas, personas con bajos ingresos económicos y quienes tienen un acceso limitado a servicios públicos [@hallegatte2017] constituyen estos intersticios discursivos, ausentes en la polifonía de la GRD.

A partir de esta premisa, la GRD no puede considerarse un proceso social si se soporta en exclusiones, segregaciones o silenciamientos, lo cual ha sido naturalizado en las expresiones cotidianas: "el trabajo con comunidades es difícil, es que las comunidades son problemáticas, es necesario desarrollar conocimiento para las comunidades." De plano, este tipo de configuraciones discursivas parte de la negación epistémica de otro que se expresa de forma diferente a la habitual, convoca un silenciamiento y una verticalización del poder, en tanto el acercamiento comunitario parte de la desconfianza y desdén. Por esta razón, referirse a un enfoque etnodiferencial en la GRD es un llamado de atención ante la práctica persistente de silenciar voces.

::: {#box1 .callout-important style="background-color: #e3f0fbff; border-left: 4px solid #d4e8f9ff;" appearance="minimal" icon="false"}
<h2 style="font-size: 1rem; margin-top: 0; margin-bottom: 0;">Caja 1. Avances en Colombia hacia una GRD participativa, inclusiva y diversa</h2>

En Colombia, se ha intentado avanzar hacia una GRD participativa, inclusiva y diversa. Dos instrumentos jurídico-políticos de relevancia lo demuestran. El primero es la Ley 1523 de 2012, mediante la cual se adopta la política nacional de gestión del riesgo de desastres y se establece el Sistema Nacional de Gestión del Riesgo de Desastres [@ley1523]. En su artículo 3ro, se definen los principios generales de la GRD. Entre estos principios, destacan dos que son relevantes para nuestro análisis.

**Principio participativo\index{Principio participativo}.** Es deber de las autoridades y entidades del Sistema Nacional de Gestión del Riesgo de Desastres, reconocer, facilitar y promover la organización y participación de comunidades étnicas, asociaciones cívicas, comunitarias, vecinales, benéficas, de voluntariado y de utilidad común. Es deber de todas las personas hacer parte del proceso de gestión del riesgo en su comunidad.

**Principio de diversidad cultural\index{Principio de diversidad cultural}.** En reconocimiento de los derechos económicos, sociales y culturales de las personas, los procesos de la gestión del riesgo deben ser respetuosos de las particularidades culturales de cada comunidad y aprovechar al máximo los recursos culturales de la misma.
:::

Con base en estos principios, solo existe un camino viable para la GRD: uno que centre su acción en las realidades y voces de las comunidades\index{voces de las comunidades}. De acuerdo con Montero [@montero2004], "lo comunitario incluye el rol activo de la comunidad, su participación. Y no sólo como invitada, o como espectadora aceptada o receptora de beneficios, sino como agente activo con voz, voto y veto" (p. 31).

Desde esta perspectiva, el enfoque etnodiferencial en la GRD requiere el conocimiento y reconocimiento de la diversidad, no como una forma de clasificar comportamientos, sino como una apuesta por lo común, por el encuentro con el otro en contextos de incertidumbre y la aceptación de su humanidad [@navarro2020; @sanchez2013].

El segundo instrumento jurídico-político relevante es el Plan Nacional de Gestión del Riesgo de Desastres "Una estrategia de Desarrollo" 2015-2025 [@ungrd2016]. En este plan, se establece como objetivo estratégico fortalecer la gobernanza, la educación y la comunicación social en la gestión del riesgo, con un enfoque diferencial, de género y de diversidad cultural. Al respecto, se señala:

El trabajo con comunidades será respetuoso del enfoque diferencial, considerando los valores culturales, religiosos y sociales, y no debe existir discriminación de ningún tipo en las acciones que el Sistema Nacional de Gestión del Riesgo (SNGRD) impulse en el territorio nacional, especialmente en relación con edad, sexo, condición social, etnias y grupos minoritarios, población indígena y comunidades afrodescendientes, y personas en situación de discapacidad (pág. 31).

En este marco, el reconocimiento de las realidades y voces comunitarias, así como su participación dialógica, conlleva al fortalecimiento de la gobernanza, la educación y la comunicación social. El objetivo es favorecer la expresión de comunidades vivas y activas, capaces de gestionar su propio entorno, en consonancia con Rodríguez y Montenegro [@rodriguez2016]:

La toma de decisiones es la manera en que la comunidad puede vivirse, la forma en que estamos con los otros u otras. He aquí, en el tratamiento de la diferencia y de la posibilidad del encuentro, donde reside el componente político y ético de lo que entendemos por comunidad (pág. 16).

Por lo tanto, la incorporación del enfoque etnodiferencial\index{enfoque etnodiferencial} en la GRD convoca a explorar sus posibilidades de articulación ---propósito de esta investigación---. Esta incorporación precisa ser vista como ejercicio ontológico dado que busca superar la subalternidad que históricamente ha caracterizado a muchas comunidades, permitiendo un reconocimiento de estas como agentes activos en la construcción de su propio mundo y como praxis transformadora en cuanto se orienta hacia la reducción de riesgos y desastres mediante el diálogo entre saberes, acciones y poderes.

# 2. METODOLOGÍA

La investigación adelantada fue de tipo cualitativa, estructurada mediante fases polifónicas. Esta noción hace referencia a estadios de diálogo que reúnen diversas voces, permitiendo que emerja un discurso generativo [@guzman2020; @lastra2020] en clave de las categorías etnodiferencial y GRD, seguidas por la pregunta amplia: ¿Cuáles son las posibilidades de articulación del enfoque etnodiferencial a la GRD en Colombia? Estas fases se complementaron con un proceso de acuerdos narrativos [@sciurano2022], mediante el cual se armonizan los tonos discursivos y operativos en colaboración con las instancias responsables del proyecto. En consecuencia, las fases polifónicas se desarrollaron de la siguiente manera:

**Fase polifónica I.** Esta fase implicó la revisión de documentos sobre el enfoque etnodiferencial en la GRD en Latinoamérica, con énfasis en Colombia. Se exploraron Google Académico, Redalyc, Scielo, Ebsco, CEPAL, Dialnet, Tesis Doctorales en Red y UNESCO, utilizando palabras clave como "etnodiferencial", "diversidad", "desastres", "riesgos", "recuperación", "rehabilitación" y "reconstrucción", en el rango temporal 2016--2021. De 213 textos iniciales, se eliminaron duplicados y no relevantes, quedando 80; la saturación categorial redujo la unidad de trabajo a 50. Este proceso aseguró una base sólida para analizar el componente étnico en la GRD. La metodología de selección aplicada refleja un enfoque transparente, alineado con los estándares de revisión, facilitando futuras investigaciones y aplicaciones prácticas en contextos étnicos diversos.

**Fase polifónica II.** En esta fase se desarrollaron narrativas generativas, donde las voces de miembros de comunidades e instituciones, sus experiencias cotidianas y sus formas de vida contribuyeron a la construcción de líneas de fuga para la incorporación del enfoque diferencial en la gestión del riesgo de desastres. Este proceso incluyó: 6 grupos focales en modalidad virtual (3 con instituciones y 3 con comunidades) y 14 entrevistas individuales en modalidad virtual (6 con representantes institucionales y 8 con representantes comunitarios).

La selección de participantes se basó en un muestreo a conveniencia [@reales2022] asegurando que fueran actores clave en el proceso. Se contó con la participación de representantes de San Andrés, Providencia y Santa Catalina, Caldas, Tolima, Cauca, Bogotá D.C., Risaralda y La Guajira, así como miembros de la Mesa Nacional de Fortalecimiento Comunitario de la Unidad Nacional para la Gestión del Riesgo de Desastres - Presidencia de la República de Colombia.

**Fase polifónica III.** Consistió en el análisis y triangulación de la información obtenida en la Fase I y la Fase II, para esto se estructuró una matriz de doble entrada o matriz de consistencia cualitativa, siguiendo los planteamientos de Giesecke [@giesecke2020], en tanto esta herramienta permite organizar, relacionar y entender los datos obtenidos. Esto se complementó aplicando el criterio de saturación categorial, consistente en la no obtención de más información nueva luego de realizado el análisis [@alaggia2020].

# 3. RESULTADOS

Los resultados han de presentarse en virtud de cuatro acápites: (1) Participación comunitaria en la GRD, (2) Conocimiento del riesgo y enfoque etnodiferencial, (3) Reducción del riesgo y enfoque etnodiferencial, (4) Manejo de desastres y enfoque etnodiferencial.

## 3.1 Participación comunitaria en la Gestión del Riesgo de Desastres

La participación comunitaria en la GRD en Colombia se ha identificado como un elemento esencial para lograr una estrategia inclusiva y eficaz. Las voces recogidas en esta investigación destacaron los siguientes aspectos clave para entender esta participación:

**Cosmovisión y cosmogonía\index{Cosmovisión y cosmogonía}.** En Colombia, las comunidades negras, afrocolombianas, raizales, palenqueras, gitana o Rrom e indígenas tienen distintas formas de comprender el mundo y su relación con el entorno. Estas cosmovisiones incluyen sistemas de deidades, prácticas socio-naturales y explicaciones sobre la interacción humana con la naturaleza. Además, las expresiones socioculturales derivadas de la colonización y el relacionamiento intercultural han dado lugar a culturas campesinas y urbanas. Es relevante que las instancias de coordinación territorial comprendan y valoren estas diversas concepciones del mundo. Al mismo tiempo, es necesario articular los conocimientos técnico-científicos en gestión del riesgo de desastres con estos saberes comunitarios. De esta manera, la gestión del riesgo puede alinearse con estas visiones, asegurando que las estrategias para la reducción del riesgo y la respuesta a emergencias sean culturalmente pertinentes.

**Organización comunitaria\index{Organización comunitaria}.** Las comunidades en Colombia presentan estructuras organizativas diversas, que pueden ser jerárquicas o horizontales, con procesos de toma de decisiones adaptados a sus contextos. Estas estructuras también definen sus relaciones con otros actores territoriales y su incidencia en la toma de decisiones conjunta. Conocer estas formas de organización es vital para que las instancias de coordinación territorial desarrollen métodos efectivos de acercamiento comunitario. La colaboración con Cabildos, Resguardos, Consejos Comunitarios, Juntas de Acción Comunal, Asociaciones Campesinas y Kumpanias (Kumpañy en plural) puede facilitar el avance de procesos de gestión del riesgo de desastres. Además, estos enfoques deben estar en línea con el marco jurídico, político y organizativo que ampara a estas comunidades.

**Toma de decisiones conjunta.** El riesgo y el desastre son conceptos construidos socialmente, derivados de la historia de relaciones e interacciones dentro de un territorio. De esta manera, la reducción del riesgo y del desastre es también un proceso social y relacional. Aquí, las instancias de coordinación territorial enfrentan tensiones, porque la toma de decisiones sobre un territorio específico debe incluir la voz de las comunidades, su participación activa, y la posibilidad de vetar acciones concretas, todo esto en consonancia con los marcos jurídico-políticos aplicables, como la consulta previa.

La participación de las comunidades en el proceso de toma de decisiones es esencial para que estas instancias se sientan informadas y vinculadas a dichos procesos. Por ello, las entidades gubernamentales tienen la responsabilidad de minimizar las barreras que puedan excluir a las comunidades de estos espacios decisorios. Asimismo, es crucial que se fomente la participación de las comunidades en el diseño e implementación de políticas públicas que reflejen la realidad del territorio.

La garantía de participación de las comunidades contribuye a la construcción de un conocimiento bidireccional, lo que puede fortalecer tanto la institucionalidad como el empoderamiento comunitario. Este proceso debe ser sensible a las cosmovisiones, cosmogonías y formas de organización particulares de cada comunidad, para asegurar una toma de decisiones que respete y refleje las realidades locales.

**Articulación de las instancias de coordinación territorial y las comunidades.** La articulación entre las instancias de coordinación territorial y las comunidades se encuentra en una tensión constructiva, donde la inclusión de representantes comunitarios con legitimidad y reconocimiento en sus territorios se vuelve crucial. Estos representantes, participan activamente y de manera permanente en los Consejos departamentales, distritales y municipales de Gestión del Riesgo de Desastres, y, cuando sea necesario, en instancias de coordinación para la respuesta a emergencias y desastres, dan forma a un proceso más inclusivo y representativo.

Estos consejos y espacios de coordinación actúan como foros de organización, asesoría, planeación y seguimiento, creando un entorno propicio para la participación comunitaria. A través de esta participación, se generan diálogos y decisiones que reflejan las realidades locales y permiten a las comunidades influir en los procesos relacionados con la gestión del riesgo de desastres en sus territorios. La inclusión de estas voces comunitarias asegura que las acciones y estrategias desarrolladas en estos contextos estén conectadas con las necesidades y expectativas de quienes viven en esas áreas. Esta articulación debe propender mínimamente por tres elementos ([Caja 2](#box2)).

::: {#box2 .callout-important style="background-color: #e3f0fbff; border-left: 4px solid #d4e8f9ff;" appearance="minimal" icon="false"}
<h2 style="font-size: 1rem; margin-top: 0; margin-bottom: 0;">Caja 2. Elementos mínimos que la articulación debe favorecer</h2>

**Refuerzo de las garantías constitucionales\index{garantías constitucionales} a los grupos étnicos.** Reforzar las garantías constitucionales de los miembros de los Pueblos Negros, Afrocolombianos, Palenqueros; los Pueblos Indígenas; el Pueblo Rrom y el Pueblo Raizal del Archipiélago de San Andrés, Providencia y Santa Catalina, adoptando medidas para garantizar la asistencia humanitaria, la protección y la reconstrucción de infraestructura y viviendas como consecuencia de los desastres, evitando toda discriminación y asegurando la máxima protección de su identidad y patrimonio cultural. Este enfoque plantea tensiones respecto a la forma en que se maneja el desastre y cómo se gestiona el riesgo, requiriendo una visión integral que considere las particularidades culturales de estos grupos étnicos en cada etapa del proceso.

**Respeto de la consulta previa\index{consulta previa} y el consentimiento previo libre e informado.** Garantizar los derechos a la Consulta Previa y el Consentimiento Previo Libre e Informado de los Pueblos Negros, Afrocolombianos, Palenqueros; los Pueblos Indígenas; el Pueblo Rrom y el Pueblo Raizal del Archipiélago de San Andrés, Providencia y Santa Catalina, en todas las decisiones relacionadas con la gestión del desastre. Esto incluye las etapas de prevención, atención, reconstrucción y reubicación de viviendas o poblados, así como la determinación de modelos económicos, sociales, culturales y ambientales para su futuro. Estas necesidades generan tensiones entre los derechos de las comunidades y las estructuras institucionales, haciendo imperativa la búsqueda de altos niveles de concertación y participación. Se debe promover el fortalecimiento de espacios de interlocución, participación y representatividad, junto con el impulso de procesos organizativos internos de estos pueblos.

**Protección de derechos territoriales\index{Protección de derechos territoriales} de los grupos étnicos.** Establecer medidas para proteger los derechos territoriales de los Pueblos Negros, Afrocolombianos, Palenqueros; los Pueblos Indígenas; el Pueblo Rrom y el Pueblo Raizal del Archipiélago de San Andrés, Providencia y Santa Catalina. La protección de la propiedad, tanto individual como colectiva, requiere considerar títulos formales, posesiones ancestrales y herencias familiares generacionales. Esta protección involucra tensiones que exigen equilibrar las prácticas consuetudinarias y los derechos de propiedad, en un contexto donde la legalidad y las tradiciones convergen, estableciendo un compromiso que respete la diversidad y los usos propios de estos pueblos.
:::

**Diversidad e inclusión\index{Diversidad e inclusión}.** Las instancias de coordinación territorial se encuentran ante la necesidad de reconocer y comprender las diversas dinámicas culturales, históricas, educativas, laborales y económicas que definen a mujeres, niños, niñas, jóvenes, adultos, la comunidad LGBTIQ+, personas con discapacidad, comunidades negras, afrocolombianas, raizales, palenqueras, gitanas o Rrom, indígenas, campesinas y comunidades urbanas en sus territorios. Este reconocimiento demanda escenarios de participación que reflejen las realidades contextuales y garanticen un marco de protección y derechos. Esta tensión sugiere que se consideren líneas de fuga para hacer posible la participación efectiva de estos distintos grupos, adaptándose a sus necesidades particulares: desde diseño universal y ayudas técnicas, hasta ajustes razonables y materiales informativos adaptados. También implica la disponibilidad de entornos físicos adecuados, horarios flexibles, rutas de fácil acceso y la presencia de intérpretes. Este enfoque cuestiona las estructuras tradicionales, impulsando un replanteamiento que favorezca la inclusión auténtica y el respeto por la diversidad.

**Instrumentos de consulta\index{Instrumentos de consulta} para fomentar la participación comunitaria:** el repositorio de la Unidad Nacional para la Gestión del Riesgo de Desastres dispone de un amplio conjunto de recursos que serán de utilidad para las instancias territoriales. Entre ellos son de relevancia: Estudio de diagnóstico de la integración de la inclusión y la protección en el plan nacional de gestión del riesgo de desastres en Colombia [@hanashiro2020], El enfoque diferencial en la gestión del riesgo de desastres: etnia, género y discapacidad [@ungrd2019], Guía para la participación comunitaria en la gestión del riesgo de desastres [@ungrd2017], Guía comunitaria para la gestión del riesgo de desastre [@ungrd2013]. Dado que este instrumento está en constante actualización, se recomienda su revisión periódica. En complemento, se invita a consultar la lista de planes de salvaguarda y planes de vida, así como la Guía para la formulación de Planes de Etnodesarrollo en Consejos Comunitarios albergados en el Ministerio del Interior de Colombia.

## 3.2 Conocimiento del riesgo y enfoque etnodiferencial\index{Enfoque etnodiferencial}

En el contexto del conocimiento del riesgo, los participantes en este proceso identificaron elementos fundamentales para la construcción de una vida digna: la diversidad de perspectivas, el diálogo de saberes, y el respeto por las cosmovisiones de las comunidades, todo ello en un marco de inclusión y participación significativa, así encontramos:

**Identificación de escenarios de riesgo.** Comprender los escenarios de riesgo implica conocer los procesos históricos que han dado forma a los territorios. Esta comprensión genera tensiones en la relación entre amenaza y vulnerabilidad, ya que estos factores pueden manifestarse de manera única para cada grupo poblacional. Desde esta perspectiva, las líneas de fuga emergen al considerar que cada comunidad tiene capacidades diferenciadas que se han desarrollado a lo largo de su historia y que están vinculadas a sus tradiciones, usos y costumbres. El reconocimiento de estas capacidades abre trayectorias para abordar las vulnerabilidades, permitiendo que las comunidades tengan un rol activo en la identificación de escenarios de riesgo.

La importancia de estas capacidades radica en que constituyen conocimientos acumulados que han permitido a estas comunidades reducir riesgos y responder a emergencias y desastres. En este contexto, priorizar el análisis de capacidades y saberes tradicionales genera oportunidades para una apropiación social del conocimiento, que articula el saber científico con otros saberes ancestrales, creando enfoques integrales para la gestión del riesgo. Estas reflexiones también revelan disyuntivas al tratar de equilibrar enfoques científicos con conocimientos tradicionales, mostrando que la gestión del riesgo requiere un entendimiento amplio y flexible de los contextos y las dinámicas de las comunidades.

**Análisis y evaluación del riesgo\index{Análisis y evaluación del riesgo}.** El análisis y la evaluación del riesgo deben abordar las tensiones y divergencias que surgen al considerar las realidades comunitarias, incluyendo historia, cultura, ancestralidad, usos y costumbres, cosmogonía y cosmovisión. Para realizar esta valoración de manera inclusiva, es necesario ajustar el lenguaje y articular los saberes técnicos, académicos e institucionales con el conocimiento comunitario. La convergencia de estos saberes puede generar líneas de fuga que permitan abordar el riesgo desde una perspectiva más amplia.

Conceptos como amenaza natural, exposición, vulnerabilidad y afrontamiento, aunque comunes en el lenguaje técnico, pueden no tener el mismo significado en el ámbito comunitario. Estas disyuntivas requieren una articulación cuidadosa entre diferentes grupos, reconociendo que el lenguaje técnico puede no capturar completamente las experiencias y percepciones de las comunidades. La necesidad de un lenguaje común plantea desafíos que exigen un acercamiento respetuoso y participativo, permitiendo la construcción de entendimientos compartidos para facilitar el proceso de evaluación del riesgo. Este proceso implica encuentros donde las distintas partes puedan trabajar para conciliar conceptos, reconociendo que la percepción de riesgo puede variar según el contexto cultural y la historia de cada comunidad.

**Monitoreo y seguimiento del riesgo\index{Monitoreo y seguimiento del riesgo}.** Las comunidades negras, afrocolombianas, raizales, palenqueras, gitanas (o Rrom), así como las indígenas y campesinas, desde sus propias cosmovisiones, cosmogonías, organizaciones comunitarias y prácticas culturales, poseen un conocimiento íntimo de sus territorios, identificando cambios que pueden afectarles. Estas percepciones cotidianas son fundamentales para entender el riesgo y generan tensiones con las estructuras de monitoreo tradicional. Por ello, las instancias de coordinación territorial, en diálogo con las organizaciones comunitarias, necesitan crear mecanismos de seguimiento que reflejen estas prácticas ancestrales e históricas, fomentando el diálogo de saberes y el fortalecimiento conjunto. Este enfoque implica recorridos divergentes que confluyen en un monitoreo del riesgo más sensible a las realidades comunitarias.

**Comunicación del riesgo\index{Comunicación del riesgo}.** Las instancias de coordinación territorial se enfrentan al desafío de establecer estrategias de comunicación con las comunidades que sean sistemáticas y diferenciadas, basadas en la concepción de riesgo propia de cada grupo. Esta comunicación debe ir más allá de un lenguaje técnico, reconociendo que este puede generar confusión en lugar de claridad. Las tensiones aquí se reflejan en la necesidad de integrar la lengua, los modismos y las expresiones comunitarias para facilitar el entendimiento.

Conceptos como riesgo, amenaza, vulnerabilidad y capacidad pueden tener significados muy distintos en cada comunidad, lo que sugiere la necesidad de articular diálogos que respeten las palabras y formas de cotidianidad propias. Privilegiar el uso del idioma nativo y producir materiales adaptados a criterios de accesibilidad para personas con discapacidad son líneas de fuga para asegurar una comunicación inclusiva. El uso de un lenguaje coherente y respetuoso, evitando expresiones despectivas, se vuelve clave para superar barreras culturales y promover la inclusión.

## 3.3 Reducción del riesgo y enfoque etnodiferencial\index{Reducción del riesgo y enfoque etnodiferencial}

En la búsqueda de reducir el riesgo, quienes participaron en este proceso subrayaron elementos fundamentales que merecen reflexión filosófica.

**Intervención correctiva\index{Intervención correctiva}.** La reducción de la exposición, la disminución de la vulnerabilidad o el incremento de las capacidades, plantean tensiones críticas sobre la inclusión de las comunidades. No se trata solo de informar; el proceso debe ser un diálogo sostenido en el que las comunidades asuman un papel protagónico en la identificación del riesgo y la formulación de respuestas. Esta relación dialógica se nutre del reconocimiento de la estructura organizativa, cosmovisión y cosmogonía propias de cada comunidad. Para esto, las metodologías participativas como la Investigación Acción Participativa (IAP), Investigación Acción (IA), así como la diversidad de enfoques para capturar percepciones desde la heterogeneidad de los grupos poblacionales, permiten construir puentes de entendimiento. Las prácticas ancestrales y comunitarias, como la minga, los círculos de la palabra, los rituales de limpieza, y el uso de plantas medicinales, operan como vehículos para la interacción y la reducción del riesgo, introduciendo líneas de fuga que respetan las raíces culturales.

**Intervención prospectiva\index{Intervención prospectiva}.** El desafío es evitar la creación de nuevos riesgos, una tarea que invita a la confluencia de saberes institucionales, comunitarios y académicos. Las instancias de coordinación territorial están llamadas a forjar acuerdos que reflejen las visiones ecosistémicas de las comunidades, situando la planificación estructural y no estructural en un contexto que honra las formas de organización tradicionales. Este diálogo interdisciplinario y transcultural implica una reconfiguración del proceso de planificación, asegurando que las estrategias de gestión del riesgo estén alineadas con los valores y las prácticas ancestrales de las comunidades. Así, emerge una convergencia entre modernidad y tradición que invita a reconsiderar el equilibrio entre enfoques racionales y saberes ancestrales, facilitando una reducción del riesgo que es tanto inclusiva como respetuosa de la diversidad cultural.

## 3.4 Manejo de desastres y enfoque etnodiferencial\index{Manejo de desastres y enfoque etnodiferencial}

Quienes participantes en este proceso señalaron elementos clave que delinean nuevas trayectorias para la preparación y respuesta:

**Preparación para la respuesta\index{Preparación para la respuesta}.** Los primeros en responder ante una emergencia o desastre son siempre los habitantes del territorio. Desde sus formas de organización y conocimientos ancestrales, llevan a cabo acciones basadas en sus prácticas culturales y costumbres. Aquí, las tensiones emergen cuando se trata de definir procesos de coordinación, sistemas de alerta, capacitación, equipamiento, centros de reserva y albergues. Es necesario que estos elementos estén en sintonía con las prácticas y estructuras comunitarias. La diversidad étnica, de género, edad y discapacidad debe reconocerse y reflejada en estos procesos, creando líneas de fuga que permiten la participación activa de las comunidades. La armonización de estos preparativos con el conocimiento del riesgo y las estrategias de reducción previamente desarrolladas contribuye a una respuesta más eficaz y sensible al contexto.

**Articulación interinstitucional y comunitaria\index{Articulación interinstitucional y comunitaria}.** El manejo de desastres exige una interacción entre diversas instituciones y sectores, pero esta articulación puede generar divergencias cuando las prácticas institucionales no se alinean con las formas de organización comunitarias. La necesidad de un lenguaje y protocolos homogéneos contrasta con la riqueza de las estructuras tradicionales de las comunidades. Aquí, el reto es equilibrar el rigor institucional con la diversidad cultural, permitiendo que las personerías jurídicas y la cosmovisión de cada comunidad sean parte integral del proceso. La voz y participación directa de las comunidades actúan como catalizadores para crear enfoques más inclusivos y respetuosos, evitando que la estandarización reemplace el entendimiento profundo de las particularidades locales. La articulación debe, por tanto, ser un espacio de diálogo que respete y acoja las diferencias.

**Múltiple afectación\index{Múltiple afectación}.** las emergencias y desastres construidos socialmente en los territorios coexisten con otros fenómenos sociales de igual complejidad como la violencia armada, delincuencia común y expresiones diversas de la violencia (simbólica, económica, sexual, psicológica, de género), razón por la cual es pertinente que las instancias de coordinación territorial en articulación con las comunidades y demás instituciones pertinentes, identifiquen como estos fenómenos pueden interferir en la construcción de los preparativos para la respuesta, de tal manera que definan las acciones necesarias para procurar una respuesta integral, en diferentes contextos y a diferentes tipos de amenazas, asegurando la protección de la población en toda su diversidad.

**Usos y costumbres\index{Usos y costumbres}.** Las instancias de coordinación territorial definirán de forma conjunta con las comunidades las estrategias de protección y conservación de las practicas alimentarias, económicas, vestuario, lengua, festividades, danzas, hábitos religiosos, espirituales y/o ancestrales, así como todos aquellos elementos que salvaguarden la vida cotidiana los territorios y los recursos naturales de las comunidades, y estén en concordancia con sus formas de organización, cosmovisión y cosmogonía. A su vez, acompañarán, hasta donde las comunidades lo decidan, los ejercicios de transformación cultural que posibiliten conocer y reducir el riesgo, así como realizar procesos de manejo de emergencias y desastres. Estos elementos se considerarán para la formulación y actualización de la estrategia de respuesta municipal y/o departamental.

**Preparación para la recuperación\index{Preparación para la recuperación}.** La recuperación, para las comunidades negras, afrocolombianas, raizales, palenqueras, gitanas o Rrom e indígenas, está profundamente arraigada en sus cosmogonías y cosmovisiones, reflejando una conexión simbiótica con el entorno y sus tradiciones. Estas comunidades desarrollan rituales de recuperación que no solo son actos simbólicos, sino también estrategias profundamente arraigadas en su historia y su identidad colectiva. La intervención de instancias de coordinación territorial en estos contextos debe abordar tensiones que emergen entre prácticas ancestrales y enfoques modernos de gestión de desastres. Aquí, el conocimiento de los rituales y su reconocimiento son fundamentales para la cocreación de planes de recuperación que respeten tanto elementos estructurales como no estructurales. La interacción con estas prácticas culturales implica un diálogo donde las líneas de fuga permiten que la sabiduría ancestral guíe el proceso. Los preparativos para la recuperación no pueden desvincularse del conocimiento y las estrategias de reducción del riesgo ya existentes, subrayando la importancia de la continuidad y el respeto por las prácticas tradicionales.

**Articulación interinstitucional y comunitaria\index{Articulación interinstitucional y comunitaria}.** La recuperación posdesastre revela la complejidad inherente a la articulación de múltiples instancias a nivel comunitario, municipal, departamental, nacional e internacional. Esta diversidad de actores puede generar divergencias, particularmente cuando se trata de equilibrar decisiones operativas con el respeto a las dinámicas ancestrales, culturales y comunitarias. La participación de las comunidades en este proceso se convierte en una tensión central, que exige un enfoque sensible a sus formas de organización, cosmovisión, cosmogonía, y su derecho a la autonomía y autodeterminación.

La recuperación se transforma en un proceso de múltiples trayectorias, donde las voces comunitarias deben ser parte integral del diseño y ejecución de estrategias. Este enfoque sugiere que la recuperación posdesastre no es solo un retorno a la normalidad, sino un espacio para redefinir y reconstruir en consonancia con las realidades comunitarias. La integración de las comunidades en la construcción y presentación de propuestas es, por tanto, más que una formalidad; es un reconocimiento del valor epistémico de sus experiencias y saberes, abriendo vías para una recuperación que sea justa y en armonía con su legado cultural.

**Múltiple afectación\index{Múltiple afectación}.** La recuperación posterior a un desastre puede ser un proceso de múltiples capas, coexistiendo con fenómenos de conflicto armado, delincuencia común y diversas expresiones de violencia, sin mencionar otros riesgos de desastre. Estas interacciones generan tensiones que las instancias de coordinación territorial deben abordar de manera conjunta con las comunidades y otras instituciones pertinentes. El desafío es crear análisis complejos que conduzcan a la construcción de un plan de recuperación integral, capaz de lidiar con esta multiplicidad de amenazas mientras mantiene un enfoque coherente con las realidades territoriales. Aquí, las líneas de fuga surgen de la capacidad de entrelazar estrategias para abordar la diversidad de riesgos y ofrecer respuestas flexibles y adaptativas.

**Usos y costumbres\index{Usos y costumbres}.** El proceso de rehabilitación, reparación o reconstrucción de áreas afectadas por emergencias o desastres debe tener en cuenta la protección y conservación de prácticas tradicionales, como las alimentarias, ecosistémicas, económicas, el vestuario, la lengua, las festividades, las danzas y los hábitos religiosos, espirituales y ancestrales. El respeto por estos elementos no solo garantiza la continuidad de la vida cotidiana de las comunidades, sino que también establece trayectorias de reconstrucción que están en armonía con sus formas de organización, cosmovisión y cosmogonía. Definir estos planes de recuperación en consonancia con los usos y costumbres implica un profundo reconocimiento de la riqueza cultural de cada territorio y genera un sentido de propiedad compartida sobre el proceso de reconstrucción.

**Ejecución de la respuesta y la recuperación\index{Ejecución de la respuesta y la recuperación}.** La atención de emergencias y desastres, junto con la recuperación posterior, es un proceso altamente complejo y dinámico, donde las circunstancias pueden cambiar rápidamente. Estas disyuntivas requieren que las instancias de coordinación territorial garanticen que las comunidades tengan una representación activa en todos los niveles de toma de decisiones, desde el Comando Único y el Comando Unificado hasta los comités de recuperación. El reconocimiento de las diversas formas de organización comunitaria y la articulación con sus procesos de autogestión son esenciales para mantener un enfoque centrado en las necesidades y perspectivas de las comunidades. Este enfoque genera espacios donde la diversidad cultural y las prácticas tradicionales guían la toma de decisiones, permitiendo una respuesta y recuperación más inclusivas y acordes con las sensibilidades locales.

# 4. DISCUSIÓN Y CONCLUSIONES

El enfoque etnodiferencial presenta una multiplicidad de alternativas que convocan caminos para otras formas de sentipensar la GRD en Colombia. Al considerar las tensiones que emergen, se permite una interacción entre los saberes ancestrales y las estructuras modernas de GRD, así como un replanteamiento de la participación comunitaria, la articulación interinstitucional y el papel de los saberes comunitarios en la construcción del conocimiento.

El discurso predominante en la GRD ha sido históricamente monolítico, estructurado desde una visión occidental y tecnocrática que, al mismo tiempo, margina las experiencias y conocimientos de las comunidades. Ante este panorama, se presenta una línea de fuga fundamental: la reconstrucción del espacio discursivo para reconocer la voz a las cosmovisiones, cosmogonías y prácticas ancestrales que han sido sistemáticamente silenciadas. Este enfoque etnodiferencial busca descentralizar el conocimiento hegemónico y colocar en primer plano las voces de las comunidades negras, afrocolombianas, raizales, palenqueras, gitanas (o Rrom) e indígenas, redefiniendo su papel de la periferia al centro de la acción.

Tal como lo expresan Amorim et al. [@amorim2022], un giro conceptual es indispensable para desafiar el planeamiento excluyente. Su propuesta de un enfoque basado en el lugar (place-based and place-making) es relevante para reconocer y valorar el conocimiento tradicional y local que ha sido invisibilizado. Los autores argumentan que los enfoques convencionales de adaptación son fragmentados y tecnocráticos, pasando por alto las vulnerabilidades superpuestas de los habitantes históricamente marginados. De este modo, la justicia climática interseccional que defienden demanda la integración del conocimiento, alejándose de los modelos impulsados por expertos. Esta idea respalda directamente la necesidad de un enfoque etnodiferencial, ya que el lugar saca a la luz las complejidades de las geografías racializadas, formadas por historias de (neo)colonialismo y racismo contemporáneo.

La necesidad de esta reestructuración del poder discursivo es reforzada por Andreucci y Zografos [@andreucci2022], quienes plantean el imperativo de una descolonización epistémica. El othering o alterización, entendida como una tecnología de gobierno racista y colonial, ha sido de significancia para legitimar las intervenciones climáticas y suspender la responsabilidad por sus impactos negativos. El desmantelamiento del silenciamiento epistémico, por lo tanto, no es solo un acto discursivo, sino un acto de justicia que deconstruye los discursos jerarquizadores y reafirma la capacidad del subalterno para hablar. Esta perspectiva de Andreucci y Zografos [@andreucci2022] confirma que la transformación debe ir más allá de la mera inclusión, y en su lugar, debe reconocer la pluriversalidad de las prácticas y conocimientos socioambientales no occidentales.

En complemento, la transformación requiere, tal como lo señalan Eriksen et al. [@eriksen2021], un pluralismo ontológico. La persistencia de la vulnerabilidad en las comunidades marginadas se debe a la incapacidad de las intervenciones de adaptación para comprometerse con la política, el poder y la complejidad social. Los autores critican cómo las intervenciones existentes fallan porque las dinámicas de poder inhiben la participación activa de los más marginados. Por ello, la transformación no debe recaer en que los grupos marginados cambien sus prácticas, sino en que los expertos y las organizaciones reestructuren sus propios procesos de conocimiento y aprendizaje para sintonizar con las cosmovisiones que tradicionalmente han ignorado. Esta reorientación hacia las estructuras de las organizaciones es clave para que las comunidades sean agentes activos y lideren sus propios procesos de vida digna.

La noción de subalterno en la GRD se desvanece a medida que las comunidades asumen un papel protagónico en la toma de decisiones. El enfoque etnodiferencial no solo reconoce la existencia de saberes ancestrales y locales, sino que los posiciona como elementos centrales y válidos para la construcción de soluciones contextualizadas. Este proceso, que involucra metodologías participativas como la investigación acción participativa\index{Investigación acción participativa} (IAP) y prácticas ancestrales como la minga o los círculos de la palabra, permite tensionar el discurso dominante que ha perpetuado la exclusión.

Como sostienen Díaz et al. [@diaz2025], las metodologías participativas\index{Investigación acción participativa} (IAP)son esenciales porque exigen la inclusión de los saberes situados para generar estrategias en la gestión del riesgo. Los autores subrayan que esta vinculación, al reconocer la capacidad de agencia y voz a las comunidades, contribuye a la gobernanza del riesgo mediante la articulación de múltiples voces y prácticas sociales que han sido tradicionalmente ignoradas. La IAP, en particular, facilita el diálogo entre el conocimiento científico y el saber local, permitiendo comprensiones contextualizadas de la realidad.

La adopción de estas metodologías representa un horizonte por lograr, una ruptura onto-epistémica frente a la visión hegemónica. Sandoval y Martínez [@sandoval2021] argumentan que la investigación y actuación tradicional han incurrido en un epistemicidio al soslayar los saberes no categorizados como científicos, explotando y legitimando prácticas de dominación. Frente a esto, las metodologías participativas se proponen comenzar por el conocimiento de las vidas marginalizadas. Los autores abogan por una coproducción continua de saberes sobre el riesgo, reconociendo que el conocimiento debe ser colectivo, múltiple y contradictorio.

En este sentido, las metodologías participativas son un vehículo con alto potencial transformador, como lo señalan Suazo et al. [@suazo2025]. Estos enfoques fomentan el empoderamiento local y la valorización de los saberes ancestrales, superando las perspectivas externas, tecnocráticas y exclusivamente cuantitativas que han invisibilizado a grupos como los pueblos indígenas o las mujeres rurales. La persistencia de lógicas informativas o consultivas, donde las comunidades solo proveen datos, refleja un extractivismo epistémico con escaso reconocimiento de los saberes locales. Por ello, la investigación y el abordaje de la GRD deben avanzar hacia una participación significativa y transformadora que reconozca a las comunidades como actores sociales y epistémicos.

En complemento, el reconocimiento de las capacidades diferenciadas que las comunidades han desarrollado a lo largo de su historia abre un espacio para el diálogo de saberes, donde el conocimiento científico se entrelaza con las prácticas culturales [@ramirez2016; @hernandez2020]. Esta integración no solo permite una apropiación social del conocimiento, sino que también refuerza la participación y el empoderamiento comunitario.

Esta visión se alinea con la perspectiva de Londoño et al. [@londono2024], quienes promueven el modelo de Gestión Comunitaria del Riesgo de Desastres\index{Gestión Comunitaria del Riesgo de Desastres} (CBDM). Este modelo acentúa a las comunidades como los principales expertos en sus condiciones de vulnerabilidad, en contraste con los enfoques de arriba hacia abajo. El estudio subraya que las capacidades desarrolladas previamente por las comunidades, como las prácticas de solidaridad y apoyo social, pueden mejorar significativamente la resistencia ante los desastres. Esta disposición se caracteriza por la integración sinérgica de todos los recursos disponibles, incluyendo el conocimiento ancestral con sistemas modernos de alerta temprana, lo que convierte a las comunidades en sujetos activos en la creación de sus propias estrategias.

El reconocimiento de estas capacidades es vital para contrarrestar la ciudad imaginada de la planeación oficial, un punto destacado por Rivera et al. [@rivera2020]. Los autores demuestran que la vida comunitaria en barrios informales se construye gracias al autoaprendizaje y la adaptación a las condiciones del territorio. Lejos de ser espontáneas, estas capacidades son el resultado de la articulación de voluntades y recursos no convencionales. La necesidad de este cambio de paradigma es respaldada por Valencia y Valencia [@valencia2024], quienes señalan el fracaso de los enfoques tradicionales en Colombia. Estos enfoques privilegian el análisis técnico y la definición física de la vulnerabilidad por encima de la percepción de riesgo de los grupos sociales. Los autores argumentan que la gestión del riesgo debe alejarse de un modelo que enfatiza en exceso las directrices técnicas y desatiende la participación efectiva de la comunidad.

Con base en lo expuesto, el reconocimiento de la diversidad epistémica se presenta como una fortaleza y no un obstáculo. El uso de instrumentos de consulta y la participación activa de las comunidades solo son efectivos si el saber institucional reconoce el conocimiento comunitario en equivalencia epistémica. Esta visión no solo fomenta el entendimiento mutuo, sino que propicia un replanteamiento de la GRD que abraza la diversidad cultural y promueve la inclusión.

Esta perspectiva, aún en desarrollo, va mostrando sus posibilidades. Hadlos et al. [@hadlos2022] y Vasileiou et al. [@vasileiou2022] señalan que la integración de ambos tipos de conocimiento es una forma de operacionalizar la participación, permitiendo que el saber local llene importantes vacíos de información donde los datos formales son escasos. Esta integración es un paso fundamental hacia la construcción de relaciones horizontales entre profesionales y comunidades. De hecho, existe una perspectiva emergente que concibe el conocimiento local como un sistema válido por derecho propio, más que un mero complemento [@hadlos2022], de ahí que puedan entenderse los sistemas de alerta temprana\index{Sistemas de alerta temprana} (SAT) como ser procesos sociales y comunitarios en lugar de simples herramientas tecnológicas.

En este sentido, el enfoque etnodiferencial promueve un diálogo equilibrado entre las estructuras institucionales y las comunidades. La participación activa en todos los niveles de toma de decisiones, desde los comités de GRD hasta la articulación en Comandos Únicos, garantiza que las estrategias de gestión y recuperación se alineen con las necesidades locales. Esto evita la estandarización y promueve el respeto por las formas de organización locales.

Baudoin et al. [@baudoin2016] destacan que la participación de las comunidades en la gestión de los SAT es una forma de abordar las brechas de comunicación, y que, al situarlas en control de sus propios sistemas, se fomenta compromiso y empoderamiento. Esta articulación fortalece la confianza y la colaboración entre las comunidades y los actores externos, como lo menciona Vasileiou et al. [@vasileiou2022]. Sin embargo, es fundamental prestar atención a las dinámicas de poder para asegurar que la participación sea genuina y no simplemente consultiva. Finalmente, la necesidad de no estandarizar es un punto recurrente, de ahí que el trabajo en GRD requiera ser flexible y adaptado a las necesidades/capacidades de cada grupo, garantizando que la información sea comprensible y culturalmente apropiada para todos.

Para finalizar, la presente investigación nos permite afirmar que el enfoque etnodiferencial en la GRD en Colombia abre líneas de fuga que sugieren un replanteamiento de la gestión del riesgo como un proceso eminentemente social, donde el diálogo y el respeto por la diversidad emergen como rizomas fundamentales. Al desarticular la noción de subalterno y promover una comprensión de las dinámicas comunitarias, se construye un espacio para una gestión del riesgo que no solo busca minimizar el sufrimiento, sino también impulsar la justicia, la dignidad y el reconocimiento pleno de todas las voces.

::: {#puntos-clave .callout-important style="background-color: #f8f0ddff; border-left: 4px solid #f7eed3ff;" appearance="minimal" icon="false"}
<h2 style="font-size: 1.5rem; margin-top: 0; margin-bottom: 0;">Puntos Clave</h2>

1. Subalternización y exclusión en la gestión del riesgo: Históricamente, las comunidades étnicas en Colombia han sido marginadas en la toma de decisiones sobre la gestión del riesgo de desastres (GRD). El enfoque etnodiferencial busca reconocer y valorar sus conocimientos y experiencias.

2. Diálogo de saberes y participación comunitaria: Integrar los conocimientos ancestrales y comunitarios con los enfoques técnicos y científicos y la participación activa de estas comunidades es necesaria para una gestión del riesgo más inclusiva y efectiva.

3. Marco legal y derechos colectivos: La Ley 1523 de 2012 y el Plan Nacional de Gestión del Riesgo de Desastres 2015-2025 establecen principios de participación y diversidad cultural en la GRD. Sin embargo, su aplicación efectiva aún enfrenta desafíos.

4. Tensiones entre enfoques fisicalistas y construccionistas: Existen enfoques que priorizan el estudio de las amenazas naturales, mientras que otros consideran el riesgo como un fenómeno social. Existe la necesidad de una perspectiva integral que incluya ambos enfoques y respete la diversidad cultural.

5. Estrategias de articulación y gobernanza: Se proponen mecanismos para fortalecer la inclusión de comunidades en la planificación y toma de decisiones, promoviendo la consulta previa, la protección de derechos territoriales y el respeto por las cosmovisiones locales en la gestión del riesgo.
:::

::: {#preguntas .callout-important style="background-color: #f3eaf8ff; border-left: 4px solid #efe3f7ff;" appearance="minimal" icon="false"}
<h2 style="font-size: 1.5rem; margin-top: 0; margin-bottom: 0;">Preguntas por resolver</h2>

1. ¿Cómo se puede garantizar que la implementación del enfoque etnodiferencial no se quede solo en el discurso institucional, sino que se materialice en acciones concretas en todos los territorios?

2. ¿Qué mecanismos de seguimiento y evaluación son necesarios para medir el impacto real de las metodologías participativas en el fortalecimiento de las capacidades comunitarias?

3. ¿De qué manera se pueden superar las tensiones que surgen entre los protocolos institucionales estandarizados y las prácticas culturales diversas de las comunidades en situaciones de emergencia?
:::

::: {#recomendaciones .callout-important style="background-color: #f8dedcff; border-left: 4px solid #fad4d1ff;" appearance="minimal" icon="false"}
<h2 style="font-size: 1.5rem; margin-top: 0; margin-bottom: 0;">Recomendaciones para tomar decisiones</h2>
1. Garantizar la Participación Activa de las Comunidades. Las comunidades étnicas deben ser actores clave en todas las fases de la gestión del riesgo (prevención, respuesta y recuperación). No basta con consultarlas; se debe asegurar su voz, voto y veto en los procesos de toma de decisiones.

2. Adoptar un Enfoque de Diálogo de Saberes. El conocimiento técnico-científico debe complementarse con los saberes ancestrales para una gestión del riesgo más efectiva y culturalmente pertinente.

3. Fortalecer el Marco Jurídico y su Aplicación. Aunque la Ley 1523 de 2012 y el Plan Nacional de GRD reconocen la diversidad cultural, su implementación sigue siendo limitada. Se recomienda crear mecanismos de veeduría comunitaria para supervisar la aplicación de políticas de GRD con enfoque etnodiferencial. Revisar y actualizar los instrumentos de planeación territorial para que incluyan el enfoque diferencial de manera obligatoria. Promover incentivos para proyectos de reducción del riesgo liderados por comunidades étnicas y financiados por fondos públicos y privados.

4. Desarrollar Estrategias de Recuperación Culturalmente Sensibles. La recuperación post-desastre debe respetar la identidad y las prácticas de las comunidades afectadas.
:::

# AGRADECIMIENTOS

Agradecemos especialmente a los líderes y lideresas comunitarios, así como a los representantes institucionales que compartieron sus ideas durante esta investigación. Su valiosa colaboración fue fundamental para llevarla a cabo. También agradecemos a Humanity & Inclusion Colombia por financiar el proyecto, identificado con el código C61-SER0301. Finalmente, expresamos nuestra sincera gratitud a la Unidad Nacional para la Gestión del Riesgo de Desastres -Presidencia de la República de Colombia-, cuyo apoyo nos permitió establecer contacto con representantes comunitarios e instituciones para el desarrollo de las conversaciones.

# CONFLICTO DE INTERESES

El autor y la autora no declaran conflicto de intereses.

# USO DE HERRAMIENTAS DE INTELIGENCIA ARTIFICIAL

Durante la preparación de este capítulo, los autores utilizaron ChatGTP versión 3.5 (https://chat.openai.com/) con el fin de recibir sugerencias de redacción y corrección del estilo científico.

Los revisores expresan que no utilizaron herramientas de IA en el proceso de evaluación del manuscrito.

# IDENTIFICACIÓN DE AUTORES

- William Oswaldo Gaviria Gutiérrez: <https://orcid.org/0000-0003-4228-4665>
- Lina Andrea Zambrano Hernández: <https://scholar.google.es/citations?user=KHLJGVwAAAAJ&hl=es>

# DECLARACIÓN DE AUTORÍA CRediT

**Conceptualización:** William Oswaldo Gaviria Gutiérrez y Lina Andrea Zambrano Hernández. **Metodología:** William Oswaldo Gaviria Gutiérrez y Lina Andrea Zambrano Hernández. **Redacción - borrador original:** William Oswaldo Gaviria Gutiérrez. **Administración del proyecto:** Lina Andrea Zambrano Hernández. **Búsqueda de evidencia:** William Oswaldo Gaviria Gutiérrez.

# BIBLIOGRAFÍA

::: {#refs}
:::