# Prólogo {.unnumbered}

Colombia es un país con grandes contrastes. Ocupa el segundo lugar en biodiversidad, además de ser pluricultural y multiétnico evidente en sus numerosas etnias, lenguas y tradiciones, así como también por el origen de su población. Según cifras del DANE, el 10.6% de la población colombiana es afrodescendiente, el 3.4% indígena, el 0.01% gitana y el 85 % mestiza. Así mismo, Colombia también presenta contrastes en su topografía y fuentes hídricas; desde sistemas montañosos como la cordillera de los Andes, hasta extensas llanuras orientales, costas y valles interandinos.

Todo lo anterior se traduce en una gran riqueza biológica, cultural y paisajística, que hacen de Colombia un lugar atractivo para los actores que generan conocimiento científico y técnico, quienes valoran esta riqueza y sus complejas interacciones que también se reflejan en la ocurrencia de desastres.  La particular ubicación geográfica del país le expone a amenazas hidroclimáticas y geológicas. Por ubicarse en el denominado “Cinturón de Fuego del Pacifico”, se expone a sismos y erupciones volcánicas; mientras que su fortaleza hídrica, que se manifiesta en sus dos océanos y la red hidrográfica que recorre todo el territorio, hacen que ocurran a inundaciones, movimientos en masa y huracanes.

Este año 2025, recordamos que hace 40 años ocurrió la mayor catástrofe de la historia de Colombia, la tragedia de Armero, donde se perdieron miles de vidas humanas y la destrucción de todo el municipio. Este hecho motivó al país a reconocer las amenazas volcánicas y a mejorar la gestión de riesgos de desastres, cambiando la visión de Colombia sobre los riesgos. Desde entonces, se han tomado importantes decisiones en política pública como la creación del Sistema Nacional para la Prevención y Respuesta a Desastres, (hoy Sistema Nacional para la Gestión de Riesgos de Desastres, SNGRD), se fortalecieron los sistemas de monitoreo de volcanes, se involucraron las acciones de prevención en los planes de Ordenamiento Territorial, y se reforzaron los sistemas de alerta temprana que permiten difundir a la población información sobre peligros y amenazas a las que se exponen.

Teniendo en cuenta que “la gestión del riesgo no es un acto aislado, sino una construcción colectiva que define el futuro de nuestras comunidades”, el presente libro contiene investigaciones que destacan el rol de las comunidades en la gestión del riesgo de desastres fortaleciendo el enfoque integral, participativo y coordinado.

Las comunidades son quienes conocen con precisión su territorio sea rural o citadino; por lo tanto, pueden participar en la identificación de las amenazas a las que se exponen. También pueden identificar rutas de evacuación, capacitarse y realizar simulacros, tomar medidas de prevención, participar en la planificación y el desarrollo de planes que permitan la reducir su exposición a amenazas y sus vulnerabilidades. Muchas intervenciones por años han trabajado en programas de formación y socialización a las comunidades, para hacerlas más resilientes y formar redes de apoyo que les permita estar preparadas para aportar en la gestión del riesgo de desastres, así como también conocer los equipos de monitoreo e identificar las alertas que estos suministran. Por lo que son las comunidades las que están llamadas a protegerse, participar en la gestión de riesgos de desastres, organizarse, prepararse y actuar en las diferentes actividades preventivas que se realicen.

Desde el Instituto Geográfico Agustín Codazzi invitamos a todos los actores del SNGRD a visitar y emplear los recursos del portal [Colombia en Mapas](https://www.colombiaenmapas.gov.co/inicio) como insumo para la gestión del riesgo de desastres. Creemos que las comunidades informadas hacen la diferencia para lograr un mejor conocimiento del riesgo, una reducción de sus vulnerabilidades y una respuesta efectiva ante los desastres. Invitamos a todos a consultar el presente libro y continuar divulgando este nuevo conocimiento con un enfoque centrado en las comunidades y en los animales.


**Leonor Aydé Rodríguez Rojas**, Instituto Geográfico Agustín Codazzi 

**Carlos Arturo García**, Representante Universidades Públicas ASCUN